version: 4.0.0.{build}

configuration: Release

nuget:
  disable_publish_on_pr: true

clone_depth: 1

test: off

build_script:
- ps: .\build.ps1

artifacts:
- path: artifacts\packages\**\*.nupkg
  name: MyGet

deploy: off
