version: 4.0.0.{build}

configuration: Release

nuget:
  disable_publish_on_pr: true

clone_depth: 1

test: off

build_script:
  - set K_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER% #temp
  - set K_BUILD_VERSION=%K_BUILD_VERSION:~-4%
  - build.cmd --quiet verify

artifacts:
  - path: artifacts\build\*.nupkg

deploy: off
